const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Behaviors.Rotate,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Particles,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Browser,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Plugins.LocalStorage,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Cnds.WillDestroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Exps.Gravity,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.PickNth,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Plugins.Particles.Acts.MoveToTop,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.JavaScriptInEvents.Estorage_Event1_Act1,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Particles.Acts.SetEffectParam,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Mouse.Acts.SetCursor2
	];
};
self.C3_JsPropNameTable = [
	{electiric: 0},
	{or_govde: 0},
	{or_baldir_sol: 0},
	{or_bas: 0},
	{Pin: 0},
	{or_yay: 0},
	{or_ip_ust: 0},
	{tree_ok: 0},
	{ok_number: 0},
	{Tween: 0},
	{or_ok: 0},
	{asansor: 0},
	{blue_govde: 0},
	{blue_bas: 0},
	{blue_bacak_sag: 0},
	{blue_yay: 0},
	{blue_ok: 0},
	{blue_ip_ust: 0},
	{or_baldir_sag: 0},
	{or_bacak_sag: 0},
	{or_bacak_sol: 0},
	{or_kol_sag: 0},
	{or_kol_sol: 0},
	{or_bilek_sol: 0},
	{or_bilek_sag: 0},
	{blue_bacak_sol: 0},
	{blue_baldir_sol: 0},
	{blue_baldir_sag: 0},
	{blue_kol_sol: 0},
	{blue_kol_sag: 0},
	{blue_bilek_sag: 0},
	{blue_bilek_sol: 0},
	{Mouse: 0},
	{or_ip_alt: 0},
	{saplandi: 0},
	{Bullet: 0},
	{LineOfSight: 0},
	{Physics: 0},
	{Sine: 0},
	{or_ok2: 0},
	{Keyboard: 0},
	{blue_ip_alt: 0},
	{ozel_ok: 0},
	{blue_ok2: 0},
	{Audio: 0},
	{ScrollTo: 0},
	{camera: 0},
	{tugla_kiran: 0},
	{apple: 0},
	{Solid: 0},
	{or_helmet: 0},
	{health: 0},
	{blue_helmet: 0},
	{or_col: 0},
	{or_helmet_icon: 0},
	{my_shield: 0},
	{blue_shield: 0},
	{bonus_bomb: 0},
	{helmet_button_upt: 0},
	{Anchor: 0},
	{adventure: 0},
	{adventure_taban_bg: 0},
	{Fade: 0},
	{gold_reward: 0},
	{BGBUTON: 0},
	{money_number_text: 0},
	{CHAPTER_TEXT: 0},
	{head_shot_text: 0},
	{tree_arrows_button_upt: 0},
	{Shield_button_upt: 0},
	{Touch: 0},
	{blue_healt_frame: 0},
	{blue_health2: 0},
	{blue_bacak_sag_clone3: 0},
	{blue_yay_clone3: 0},
	{blue_kol_sol_clone3: 0},
	{blue_kol_sag_clone3: 0},
	{blue_govde_clone3: 0},
	{blue_bilek_sol_clone3: 0},
	{blue_bilek_sag_clone3: 0},
	{blue_bas_clone3: 0},
	{blue_baldir_sol_clone3: 0},
	{blue_baldir_sag_clone3: 0},
	{blue_bacak_sol_clone3: 0},
	{blue_ip_alt_clone3: 0},
	{blue_ip_ust_clone3: 0},
	{blue_ok_clone3: 0},
	{blue_health2_clone3: 0},
	{blue_healt_frame_clone3: 0},
	{helmet_buyed_text_pwr: 0},
	{"3arrows_buyed_text_pwr": 0},
	{Shield_buyed_text_pwr: 0},
	{health_zone: 0},
	{health_particle: 0},
	{health_particle2: 0},
	{health_particle3: 0},
	{scale_text: 0},
	{kacadam: 0},
	{hommm_button: 0},
	{RewardedAdButton: 0},
	{MidgameAdButton: 0},
	{up_arrow_button: 0},
	{arrow_name2: 0},
	{shield_price_text2: 0},
	{Shield_buyed_text2: 0},
	{shield_price_text3: 0},
	{kim: 0},
	{electiric_kivilcim_or: 0},
	{skull_bacak: 0},
	{skull_govde: 0},
	{skull_bas: 0},
	{skull_kol: 0},
	{enemy_pixel_part: 0},
	{ok_missile_klavuz: 0},
	{scroll: 0},
	{first_play: 0},
	{secim: 0},
	{lock_unlock: 0},
	{DEFAULT_BUTTON_chs: 0},
	{BUYX3: 0},
	{FIRE_BUTTON_chs: 0},
	{ELECTIRIC_BUTTON_chs: 0},
	{PIXELLAR_BUTTON_chs: 0},
	{MISSILE_BUTTON_chs: 0},
	{POISON_BUTTON_chs: 0},
	{ROCKET_BUTTON_chs: 0},
	{CHOOSE_FRAME2: 0},
	{bomba: 0},
	{bomba_blues: 0},
	{"321go": 0},
	{endscrleftbtn_tank_mayhem: 0},
	{endscrrightbtn_tank_mayhem: 0},
	{endscre: 0},
	{or_scoree: 0},
	{blue_scoree: 0},
	{healthbuybutton_ugrade: 0},
	{text_ugrade: 0},
	{Arm_POWER_BAR: 0},
	{ALINANHASAR_BAR: 0},
	{VERILENHASAR_BAR: 0},
	{armpowerupgrade_price_text_ugrade: 0},
	{shieldupgrade_text_ugrade: 0},
	{healthupgrade_text_ugrade: 0},
	{verilenhasarupgrade_price_ugradet: 0},
	{button_rocket_buy3: 0},
	{HIGHSCORE_MOD_TEXT: 0},
	{FADE: 0},
	{shieldbuybutton_ugrade: 0},
	{armpowerbuybutton_ugrade: 0},
	{arrow_damage_button_ugrade: 0},
	{"3_arrowbuybutton_ugrade": 0},
	{helmetbuybutton_ugrade: 0},
	{"3arrowupgrade_price_ugrade": 0},
	{helmetupgrade_price_ugrade: 0},
	{fisek_patlayan_iz: 0},
	{Version_Text: 0},
	{BGBUTON2: 0},
	{povericon_ugrade: 0},
	{balanceicon_ugrade: 0},
	{healthicon_ugrade: 0},
	{wins_panel_black_bg: 0},
	{dead_text: 0},
	{BGBUTON3: 0},
	{BGBUTON4: 0},
	{OK_SEC_TABAN: 0},
	{upgrade_info_text: 0},
	{gold_reward_menu: 0},
	{Rotate: 0},
	{apple_tasiyici: 0},
	{ucan_kaya_clone3: 0},
	{addcoin: 0},
	{ON3: 0},
	{or_el_sol: 0},
	{or_el_sag: 0},
	{Blue_el_sag_clone_3: 0},
	{Blue_el_sol_clone_3: 0},
	{PlatformInfo: 0},
	{joybg: 0},
	{joy: 0},
	{line: 0},
	{lineangle: 0},
	{linewidht: 0},
	{iplik: 0},
	{iplik2: 0},
	{FireworkParticles: 0},
	{splash_Particles: 0},
	{ok_hit: 0},
	{ok_hit_tas_spawner: 0},
	{ok_hit2: 0},
	{poison_particles_or: 0},
	{fire_particles_or: 0},
	{pixel_particles_or: 0},
	{touch_hit: 0},
	{fire_impact_particles_or: 0},
	{col: 0},
	{missile_iz_or: 0},
	{missile_particles_or: 0},
	{bomba_fire_particles: 0},
	{"2p_blue_touch": 0},
	{"2p_orange_touch": 0},
	{on_off: 0},
	{DragDrop: 0},
	{upgradepanel_tasiyici_button: 0},
	{Browser: 0},
	{joy2: 0},
	{fire_particles_blue: 0},
	{missile_particles_blue: 0},
	{missile_iz_or_blue: 0},
	{poison_particles_blue: 0},
	{pixel_particles_blue: 0},
	{electiric_kivilcim_blue: 0},
	{fire_impact_particles_blue: 0},
	{bomb_sarapnel: 0},
	{touch_tutorial: 0},
	{TouchandPull: 0},
	{reward: 0},
	{bomb_collison: 0},
	{Health_oyun_bar: 0},
	{Arm_power_game_bar: 0},
	{arm_power_bonus: 0},
	{health_power_bonus: 0},
	{arm_zone: 0},
	{arm_particle: 0},
	{ok_hit3: 0},
	{health_power_crash: 0},
	{arm_power_crash: 0},
	{endscre2: 0},
	{hand_light: 0},
	{bomb_knife: 0},
	{bomb_fitil: 0},
	{fruit_bomb: 0},
	{or_ok2_knife_hit: 0},
	{Text: 0},
	{Text3: 0},
	{upgrade_info_text2: 0},
	{text_ugrade2: 0},
	{text_ugrade3: 0},
	{text_ugrade4: 0},
	{text_ugrade5: 0},
	{text_ugrade6: 0},
	{text_ugrade7: 0},
	{Flash: 0},
	{choose_arrow_t: 0},
	{health_text_ui: 0},
	{arm_power_text_ui: 0},
	{Sound_On_Off_Button: 0},
	{Text5: 0},
	{Text6: 0},
	{patlama: 0},
	{Text7: 0},
	{blue_body_part: 0},
	{menu_tutorial: 0},
	{arrowUnlocked: 0},
	{upgrade_zemin_ugrade: 0},
	{thunder_BUTTON_chs: 0},
	{saw_BUTTON_chs: 0},
	{fuze_BUTTON_chs: 0},
	{freeze_BUTTON_chs: 0},
	{meteor_BUTTON_chs: 0},
	{or_ayak_sol: 0},
	{or_ayak_sag: 0},
	{testere: 0},
	{Ice_CPU: 0},
	{addcoin2: 0},
	{ice: 0},
	{freeeze_particle: 0},
	{freeze_expl_particle: 0},
	{yildirim: 0},
	{meteor: 0},
	{meteor_particle: 0},
	{simsek: 0},
	{yildirim_patlama: 0},
	{meteor_uc: 0},
	{meteordalga: 0},
	{meteordalga2: 0},
	{ok_fuze: 0},
	{fuze: 0},
	{fuze_particle: 0},
	{ParticlesAmbience2: 0},
	{random_arrow_button: 0},
	{HEALTH_BAR_ugrade3: 0},
	{"2p_play_button": 0},
	{EndScore: 0},
	{ParticlesAmbience3: 0},
	{kukla1: 0},
	{kukla2: 0},
	{kukla3: 0},
	{kuklatoz: 0},
	{blue_ayak_sol_clone3: 0},
	{blue_ayak_sag_clone3: 0},
	{el: 0},
	{el1: 0},
	{el2: 0},
	{el3: 0},
	{el4: 0},
	{shield_sn_text: 0},
	{"3arrow_sn_text": 0},
	{helmet_sn_text: 0},
	{pixel_particles_boom: 0},
	{arm_power_miktar: 0},
	{health_miktar: 0},
	{arrow_damage_miktar: 0},
	{boss_konusma: 0},
	{ucan_kaya_or: 0},
	{fire_impact_particles_black: 0},
	{yildirim_expl_particle: 0},
	{Text8: 0},
	{Text9: 0},
	{unlock_reward_text: 0},
	{kan: 0},
	{splash_fizik: 0},
	{scar: 0},
	{kan_splash: 0},
	{kan_hit: 0},
	{pixe_cube: 0},
	{serbest: 0},
	{ice_cube: 0},
	{ok_drag: 0},
	{MoveTo: 0},
	{gold_reward_menu2: 0},
	{money_popup: 0},
	{money_popup2: 0},
	{gold_menu: 0},
	{head_shot_text2: 0},
	{LocalStorage: 0},
	{or_boyun: 0},
	{"2_player": 0},
	{survival_mode: 0},
	{BOOSTER_PANEL: 0},
	{BATTLE_GO: 0},
	{level_number_text: 0},
	{SKIN_BUTTON_NEXT: 0},
	{SKIN_BUTTON_PREW: 0},
	{level_text: 0},
	{fpstext: 0},
	{level_text2: 0},
	{kacadamm: 0},
	{level_progress_bar_zemin: 0},
	{progress_cube: 0},
	{level_progres_text_a: 0},
	{blue_boyun_clone3: 0},
	{ucan_kaya: 0},
	{Shield_button_game: 0},
	{tree_arrows_button_game: 0},
	{helmet_button_game: 0},
	{Arm_power_alt_bar: 0},
	{Health_oyun_alt_bar: 0},
	{slot1: 0},
	{slot2: 0},
	{slot3: 0},
	{slot_1_text: 0},
	{slot_2_text: 0},
	{slot_3_text: 0},
	{slot_cerceve_1: 0},
	{slot_cerceve_2: 0},
	{slot_cerceve_3: 0},
	{choose_slot1: 0},
	{choose_slot2: 0},
	{choose_slot3: 0},
	{TUTORYAL_JOY: 0},
	{TUTORYAL_JOY2: 0},
	{Untitled3_0001_Layer3copy: 0},
	{Untitled3_0000_Level_: 0},
	{ot1: 0},
	{ot2: 0},
	{ot3: 0},
	{ot4: 0},
	{ot5: 0},
	{ot6: 0},
	{ot7: 0},
	{ot8: 0},
	{ot9: 0},
	{ot10: 0},
	{ot15: 0},
	{level_progres_text_b: 0},
	{level_progress_bar: 0},
	{chapter: 0},
	{chapter_progress_bar: 0},
	{level____completed: 0},
	{next_level: 0},
	{revive: 0},
	{replay: 0},
	{COMPLETED_MONEY: 0},
	{level_money: 0},
	{gift_10_dk: 0},
	{reward_level_lock: 0},
	{gift_20_dk: 0},
	{gift_level: 0},
	{level__NUMBER__completed: 0},
	{sayac_10_dk: 0},
	{sayac_20_dk: 0},
	{CHAPTER_COMPLETED: 0},
	{chapterrewards: 0},
	{New_Arrow_Unlocked: 0},
	{New_Archer_Unlocked: 0},
	{level_money_effect: 0},
	{shield_health: 0},
	{treeok_health: 0},
	{helmet_health: 0},
	{helmet_health_zemin: 0},
	{treeok_health_zemin: 0},
	{shield_health_zemin: 0},
	{"3_arrow_BAR": 0},
	{shieldd_BAR: 0},
	{helmet_BAR: 0},
	{seciliok: 0},
	{lock: 0},
	{UNLOCK_CHAPTER_TEXT: 0},
	{GET_REWARDS: 0},
	{touch_tutorial_MENU: 0},
	{skin_choose_button: 0},
	{CHARACTER_TEXT: 0},
	{tips_pano: 0},
	{tutor_golge: 0},
	{loading: 0},
	{start_page_bg: 0},
	{new_patlama: 0},
	{expo_iz: 0},
	{touch_area: 0},
	{touch_area2: 0},
	{dead_shoot: 0},
	{head_shoot: 0},
	{bonusmode: 0},
	{bonuss: 0},
	{sarjor: 0},
	{arm_bitti: 0},
	{bonus_mesaj_text: 0},
	{pixel_light_or: 0},
	{poison_light_or: 0},
	{endscre3: 0},
	{"2p_sag_next": 0},
	{"2p_sag_prew": 0},
	{"2p_sol_next": 0},
	{"2p_sol_prew": 0},
	{healthicon_ugrade_or: 0},
	{sarjor_blue: 0},
	{serbest_2p_or: 0},
	{serbest_2p_blue: 0},
	{loading2: 0},
	{"1_player": 0},
	{healthicon_ugrade_blue: 0},
	{ot11: 0},
	{ot12: 0},
	{ot13: 0},
	{ot14: 0},
	{mec_testere1: 0},
	{mec_balta: 0},
	{mec_kaide: 0},
	{anglee: 0},
	{mec_uzun_kol: 0},
	{MEC_KAFA_KESEN: 0},
	{mec_carpan: 0},
	{mec_kablo: 0},
	{mec_carpan_particle: 0},
	{mec_parlama: 0},
	{duman: 0},
	{kan_fiskiye: 0},
	{Sprite: 0},
	{"2p_ui_scr": 0},
	{mec_silindir: 0},
	{"2p_player_score": 0},
	{touch_tutorial_2p_right: 0},
	{touch_tutorial_2p_left: 0},
	{keyboard_key_w: 0},
	{keyboard_key_up: 0},
	{or_fizik: 0},
	{enemy_fizik: 0},
	{enemy_archer: 0},
	{or_archer: 0},
	{hersey: 0},
	{or_body: 0},
	{enemy_body: 0},
	{dest: 0},
	{button: 0},
	{boss_fizik: 0},
	{boss_body: 0},
	{blue_archer_clone3: 0},
	{helmets: 0},
	{choose_arrow: 0},
	{blues_all: 0},
	{wait_dest: 0},
	{kemik: 0},
	{shields: 0},
	{tas_spawner: 0},
	{choose_arrow_image: 0},
	{choose_arrow_text: 0},
	{finish_menu_image: 0},
	{blue_archer_all: 0},
	{fruit_dest: 0},
	{menu_game_dest_text: 0},
	{menu_game_destroy: 0},
	{all_texts: 0},
	{game_butn: 0},
	{DestroyOutsideLayout2: 0},
	{sahnedisiyokol: 0},
	{blue_archer_all3: 0},
	{kuklafizik: 0},
	{blues_target: 0},
	{or_archer_target: 0},
	{or_archer_all: 0},
	{kanlar: 0},
	{boss_animation: 0},
	{otlar: 0},
	{finish_menu_text: 0},
	{eller: 0},
	{or_ui_lost_image: 0},
	{or_ui_lost_text: 0},
	{bomb_col: 0},
	{Text_ugradepanel: 0},
	{paticles_all: 0},
	{bonusss: 0},
	{mekanizma: 0},
	{day: 0},
	{Bonus_mode_or: 0},
	{Bonus_mode_blue: 0},
	{end_scr: 0},
	{or_helmet_kazandi: 0},
	{or_shield_kazandi: 0},
	{or_3ok_kazandi: 0},
	{Progress: 0},
	{reward_sayac: 0},
	{reward_timeLeft: 0},
	{reward_sayac2: 0},
	{reward_timeLeft2: 0},
	{tutorial: 0},
	{or_tree_ok: 0},
	{or_shield: 0},
	{secili_ok: 0},
	{health_upgrade_price: 0},
	{arrow_damage_upgrade_price: 0},
	{"3arrow_upgrade_price": 0},
	{power_upgrade_price: 0},
	{helmet_upgrade_price: 0},
	{shield_upgrade_price: 0},
	{Main_Sound: 0},
	{ses: 0},
	{blood_on_off: 0},
	{oyun_ici_ok_secim: 0},
	{slot_icin_ok_secme: 0},
	{skin_or: 0},
	{skin_blue: 0},
	{skin_onizleme: 0},
	{chapter_progress: 0},
	{chapter_progress_miktar: 0},
	{or_bullet_speed: 0},
	{enemy_bullet_speed: 0},
	{or_lost: 0},
	{or_health: 0},
	{enemy_health: 0},
	{or_score: 0},
	{blue_score: 0},
	{enemy_lost: 0},
	{boss_lost: 0},
	{boss_bullet_speed: 0},
	{boss_health: 0},
	{blue_score_clone3: 0},
	{dead_number: 0},
	{money: 0},
	{level_para: 0},
	{Headshoot_number: 0},
	{enemy_ai: 0},
	{boss_ai_: 0},
	{ai_arrow_power: 0},
	{sag_sol_fark: 0},
	{"1p_or_2p": 0},
	{boss_secili_ok_ai: 0},
	{shoot_speed: 0},
	{NEXT_OR_AGAIN: 0},
	{tree_ok_sn: 0},
	{shield_sn: 0},
	{helmet_sn: 0},
	{ai_target: 0},
	{shield_geri_sayim: 0},
	{helmet_geri_sayim: 0},
	{treeok_geri_sayim: 0},
	{mesafe_y: 0},
	{mesafe_x: 0},
	{arm_power: 0},
	{level: 0},
	{blues_renk: 0},
	{level_progres: 0},
	{level_progres_miktar: 0},
	{oyun_modu: 0},
	{saglik_iyilesme: 0},
	{kol_iyilesme: 0},
	{ilk_kan: 0},
	{Mobil_Pc: 0},
	{or_verilenhasar: 0},
	{or_armpower: 0},
	{or_alinanhasar: 0},
	{verilenhasar_skin1: 0},
	{armpower_skin1: 0},
	{alinanhasar_skin1: 0},
	{verilenhasar_skin2: 0},
	{armpower_skin2: 0},
	{alinanhasar_skin2: 0},
	{verilenhasar_skin3: 0},
	{armpower_skin3: 0},
	{alinanhasar_skin3: 0},
	{verilenhasar_skin4: 0},
	{armpower_skin4: 0},
	{alinanhasar_skin4: 0},
	{verilenhasar_skin5: 0},
	{armpower_skin5: 0},
	{alinanhasar_skin5: 0},
	{verilenhasar_skin6: 0},
	{armpower_skin6: 0},
	{alinanhasar_skin6: 0},
	{verilenhasar_skin7: 0},
	{armpower_skin7: 0},
	{alinanhasar_skin7: 0},
	{verilenhasar_skin8: 0},
	{armpower_skin8: 0},
	{alinanhasar_skin8: 0},
	{verilenhasar_skin9: 0},
	{armpower_skin9: 0},
	{alinanhasar_skin9: 0},
	{verilenhasar_skin10: 0},
	{armpower_skin10: 0},
	{alinanhasar_skin10: 0},
	{verilenhasar_skin11: 0},
	{armpower_skin11: 0},
	{alinanhasar_skin11: 0}
];

self.InstanceType = {
	or_govde: class extends self.ISpriteInstance {},
	or_baldir_sol: class extends self.ISpriteInstance {},
	or_bas: class extends self.ISpriteInstance {},
	or_yay: class extends self.ISpriteInstance {},
	or_ip_ust: class extends self.ISpriteInstance {},
	or_ok: class extends self.ISpriteInstance {},
	blue_govde: class extends self.ISpriteInstance {},
	blue_bas: class extends self.ISpriteInstance {},
	blue_bacak_sag: class extends self.ISpriteInstance {},
	blue_yay: class extends self.ISpriteInstance {},
	blue_ok: class extends self.ISpriteInstance {},
	blue_ip_ust: class extends self.ISpriteInstance {},
	or_baldir_sag: class extends self.ISpriteInstance {},
	or_bacak_sag: class extends self.ISpriteInstance {},
	or_bacak_sol: class extends self.ISpriteInstance {},
	or_kol_sag: class extends self.ISpriteInstance {},
	or_kol_sol: class extends self.ISpriteInstance {},
	or_bilek_sol: class extends self.ISpriteInstance {},
	or_bilek_sag: class extends self.ISpriteInstance {},
	blue_bacak_sol: class extends self.ISpriteInstance {},
	blue_baldir_sol: class extends self.ISpriteInstance {},
	blue_baldir_sag: class extends self.ISpriteInstance {},
	blue_kol_sol: class extends self.ISpriteInstance {},
	blue_kol_sag: class extends self.ISpriteInstance {},
	blue_bilek_sag: class extends self.ISpriteInstance {},
	blue_bilek_sol: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	or_ip_alt: class extends self.ISpriteInstance {},
	or_ok2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	blue_ip_alt: class extends self.ISpriteInstance {},
	blue_ok2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	tugla_kiran: class extends self.ISpriteInstance {},
	apple: class extends self.ISpriteInstance {},
	or_helmet: class extends self.ISpriteInstance {},
	blue_helmet: class extends self.ISpriteInstance {},
	or_col: class extends self.ISpriteInstance {},
	or_helmet_icon: class extends self.ISpriteInstance {},
	my_shield: class extends self.ISpriteInstance {},
	blue_shield: class extends self.ISpriteInstance {},
	bonus_bomb: class extends self.ISpriteInstance {},
	helmet_button_upt: class extends self.ISpriteInstance {},
	adventure: class extends self.ISpriteInstance {},
	adventure_taban_bg: class extends self.ISpriteInstance {},
	gold_reward: class extends self.ISpriteInstance {},
	BGBUTON: class extends self.ISpriteInstance {},
	money_number_text: class extends self.ITextInstance {},
	CHAPTER_TEXT: class extends self.ITextInstance {},
	head_shot_text: class extends self.ITextInstance {},
	tree_arrows_button_upt: class extends self.ISpriteInstance {},
	Shield_button_upt: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	blue_healt_frame: class extends self.ISpriteInstance {},
	blue_health2: class extends self.ISpriteInstance {},
	blue_bacak_sag_clone3: class extends self.ISpriteInstance {},
	blue_yay_clone3: class extends self.ISpriteInstance {},
	blue_kol_sol_clone3: class extends self.ISpriteInstance {},
	blue_kol_sag_clone3: class extends self.ISpriteInstance {},
	blue_govde_clone3: class extends self.ISpriteInstance {},
	blue_bilek_sol_clone3: class extends self.ISpriteInstance {},
	blue_bilek_sag_clone3: class extends self.ISpriteInstance {},
	blue_bas_clone3: class extends self.ISpriteInstance {},
	blue_baldir_sol_clone3: class extends self.ISpriteInstance {},
	blue_baldir_sag_clone3: class extends self.ISpriteInstance {},
	blue_bacak_sol_clone3: class extends self.ISpriteInstance {},
	blue_ip_alt_clone3: class extends self.ISpriteInstance {},
	blue_ip_ust_clone3: class extends self.ISpriteInstance {},
	blue_ok_clone3: class extends self.ISpriteInstance {},
	blue_health2_clone3: class extends self.ISpriteInstance {},
	blue_healt_frame_clone3: class extends self.ISpriteInstance {},
	helmet_buyed_text_pwr: class extends self.ITextInstance {},
	_3arrows_buyed_text_pwr: class extends self.ITextInstance {},
	Shield_buyed_text_pwr: class extends self.ITextInstance {},
	health_zone: class extends self.ISpriteInstance {},
	health_particle: class extends self.ISpriteInstance {},
	health_particle2: class extends self.ISpriteInstance {},
	health_particle3: class extends self.ISpriteInstance {},
	scale_text: class extends self.ITextInstance {},
	hommm_button: class extends self.ISpriteInstance {},
	RewardedAdButton: class extends self.IButtonInstance {},
	MidgameAdButton: class extends self.IButtonInstance {},
	up_arrow_button: class extends self.ISpriteInstance {},
	arrow_name2: class extends self.ITextInstance {},
	shield_price_text2: class extends self.ITextInstance {},
	Shield_buyed_text2: class extends self.ITextInstance {},
	shield_price_text3: class extends self.ITextInstance {},
	electiric_kivilcim_or: class extends self.ISpriteInstance {},
	skull_bacak: class extends self.ISpriteInstance {},
	skull_govde: class extends self.ISpriteInstance {},
	skull_bas: class extends self.ISpriteInstance {},
	skull_kol: class extends self.ISpriteInstance {},
	enemy_pixel_part: class extends self.ISpriteInstance {},
	ok_missile_klavuz: class extends self.ISpriteInstance {},
	DEFAULT_BUTTON_chs: class extends self.ISpriteInstance {},
	BUYX3: class extends self.ITextInstance {},
	FIRE_BUTTON_chs: class extends self.ISpriteInstance {},
	ELECTIRIC_BUTTON_chs: class extends self.ISpriteInstance {},
	PIXELLAR_BUTTON_chs: class extends self.ISpriteInstance {},
	MISSILE_BUTTON_chs: class extends self.ISpriteInstance {},
	POISON_BUTTON_chs: class extends self.ISpriteInstance {},
	ROCKET_BUTTON_chs: class extends self.ISpriteInstance {},
	CHOOSE_FRAME2: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	bomba_blues: class extends self.ISpriteInstance {},
	_321go: class extends self.ITextInstance {},
	endscrleftbtn_tank_mayhem: class extends self.ISpriteInstance {},
	endscrrightbtn_tank_mayhem: class extends self.ISpriteInstance {},
	endscre: class extends self.ITextInstance {},
	or_scoree: class extends self.ITextInstance {},
	blue_scoree: class extends self.ITextInstance {},
	healthbuybutton_ugrade: class extends self.ISpriteInstance {},
	text_ugrade: class extends self.ITextInstance {},
	Arm_POWER_BAR: class extends self.ISpriteInstance {},
	ALINANHASAR_BAR: class extends self.ISpriteInstance {},
	VERILENHASAR_BAR: class extends self.ISpriteInstance {},
	armpowerupgrade_price_text_ugrade: class extends self.ITextInstance {},
	shieldupgrade_text_ugrade: class extends self.ITextInstance {},
	healthupgrade_text_ugrade: class extends self.ITextInstance {},
	verilenhasarupgrade_price_ugradet: class extends self.ITextInstance {},
	button_rocket_buy3: class extends self.ISpriteInstance {},
	HIGHSCORE_MOD_TEXT: class extends self.ITextInstance {},
	FADE: class extends self.ISpriteInstance {},
	shieldbuybutton_ugrade: class extends self.ISpriteInstance {},
	armpowerbuybutton_ugrade: class extends self.ISpriteInstance {},
	arrow_damage_button_ugrade: class extends self.ISpriteInstance {},
	_3_arrowbuybutton_ugrade: class extends self.ISpriteInstance {},
	helmetbuybutton_ugrade: class extends self.ISpriteInstance {},
	_3arrowupgrade_price_ugrade: class extends self.ITextInstance {},
	helmetupgrade_price_ugrade: class extends self.ITextInstance {},
	fisek_patlayan_iz: class extends self.ISpriteInstance {},
	Version_Text: class extends self.ITextInstance {},
	BGBUTON2: class extends self.ISpriteInstance {},
	povericon_ugrade: class extends self.ISpriteInstance {},
	balanceicon_ugrade: class extends self.ISpriteInstance {},
	healthicon_ugrade: class extends self.ISpriteInstance {},
	wins_panel_black_bg: class extends self.ISpriteInstance {},
	dead_text: class extends self.ITextInstance {},
	BGBUTON3: class extends self.ISpriteInstance {},
	BGBUTON4: class extends self.ISpriteInstance {},
	OK_SEC_TABAN: class extends self.ISpriteInstance {},
	upgrade_info_text: class extends self.ITextInstance {},
	gold_reward_menu: class extends self.ISpriteInstance {},
	apple_tasiyici: class extends self.ISpriteInstance {},
	ucan_kaya_clone3: class extends self.ISpriteInstance {},
	addcoin: class extends self.ISpriteInstance {},
	ON3: class extends self.ITextInstance {},
	or_el_sol: class extends self.ISpriteInstance {},
	or_el_sag: class extends self.ISpriteInstance {},
	Blue_el_sag_clone_3: class extends self.ISpriteInstance {},
	Blue_el_sol_clone_3: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	joybg: class extends self.ISpriteInstance {},
	joy: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	lineangle: class extends self.ITextInstance {},
	linewidht: class extends self.ITextInstance {},
	iplik: class extends self.ISpriteInstance {},
	iplik2: class extends self.ISpriteInstance {},
	FireworkParticles: class extends self.IParticlesInstance {},
	splash_Particles: class extends self.IParticlesInstance {},
	ok_hit: class extends self.IParticlesInstance {},
	ok_hit_tas_spawner: class extends self.IParticlesInstance {},
	ok_hit2: class extends self.IParticlesInstance {},
	poison_particles_or: class extends self.IParticlesInstance {},
	fire_particles_or: class extends self.IParticlesInstance {},
	pixel_particles_or: class extends self.IParticlesInstance {},
	touch_hit: class extends self.IParticlesInstance {},
	fire_impact_particles_or: class extends self.IParticlesInstance {},
	missile_iz_or: class extends self.ISpriteInstance {},
	missile_particles_or: class extends self.IParticlesInstance {},
	bomba_fire_particles: class extends self.IParticlesInstance {},
	_2p_blue_touch: class extends self.ISpriteInstance {},
	_2p_orange_touch: class extends self.ISpriteInstance {},
	upgradepanel_tasiyici_button: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	joy2: class extends self.ISpriteInstance {},
	fire_particles_blue: class extends self.IParticlesInstance {},
	missile_particles_blue: class extends self.IParticlesInstance {},
	missile_iz_or_blue: class extends self.ISpriteInstance {},
	poison_particles_blue: class extends self.IParticlesInstance {},
	pixel_particles_blue: class extends self.IParticlesInstance {},
	electiric_kivilcim_blue: class extends self.ISpriteInstance {},
	fire_impact_particles_blue: class extends self.IParticlesInstance {},
	bomb_sarapnel: class extends self.ISpriteInstance {},
	touch_tutorial: class extends self.ISpriteInstance {},
	TouchandPull: class extends self.ITextInstance {},
	bomb_collison: class extends self.ISpriteInstance {},
	Health_oyun_bar: class extends self.ISpriteInstance {},
	Arm_power_game_bar: class extends self.ISpriteInstance {},
	arm_power_bonus: class extends self.ISpriteInstance {},
	health_power_bonus: class extends self.ISpriteInstance {},
	arm_zone: class extends self.ISpriteInstance {},
	arm_particle: class extends self.ISpriteInstance {},
	ok_hit3: class extends self.IParticlesInstance {},
	health_power_crash: class extends self.IParticlesInstance {},
	arm_power_crash: class extends self.IParticlesInstance {},
	endscre2: class extends self.ITextInstance {},
	hand_light: class extends self.ISpriteInstance {},
	bomb_knife: class extends self.ISpriteInstance {},
	bomb_fitil: class extends self.IParticlesInstance {},
	fruit_bomb: class extends self.IParticlesInstance {},
	or_ok2_knife_hit: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	upgrade_info_text2: class extends self.ITextInstance {},
	text_ugrade2: class extends self.ITextInstance {},
	text_ugrade3: class extends self.ITextInstance {},
	text_ugrade4: class extends self.ITextInstance {},
	text_ugrade5: class extends self.ITextInstance {},
	text_ugrade6: class extends self.ITextInstance {},
	text_ugrade7: class extends self.ITextInstance {},
	choose_arrow_t: class extends self.ITextInstance {},
	health_text_ui: class extends self.ITextInstance {},
	arm_power_text_ui: class extends self.ITextInstance {},
	Sound_On_Off_Button: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	patlama: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	blue_body_part: class extends self.ISpriteInstance {},
	menu_tutorial: class extends self.ITextInstance {},
	arrowUnlocked: class extends self.ITextInstance {},
	upgrade_zemin_ugrade: class extends self.ISpriteInstance {},
	thunder_BUTTON_chs: class extends self.ISpriteInstance {},
	saw_BUTTON_chs: class extends self.ISpriteInstance {},
	fuze_BUTTON_chs: class extends self.ISpriteInstance {},
	freeze_BUTTON_chs: class extends self.ISpriteInstance {},
	meteor_BUTTON_chs: class extends self.ISpriteInstance {},
	or_ayak_sol: class extends self.ISpriteInstance {},
	or_ayak_sag: class extends self.ISpriteInstance {},
	testere: class extends self.ISpriteInstance {},
	Ice_CPU: class extends self.ISpriteInstance {},
	addcoin2: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	freeeze_particle: class extends self.IParticlesInstance {},
	freeze_expl_particle: class extends self.IParticlesInstance {},
	yildirim: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	meteor_particle: class extends self.IParticlesInstance {},
	simsek: class extends self.ISpriteInstance {},
	yildirim_patlama: class extends self.ISpriteInstance {},
	meteor_uc: class extends self.ISpriteInstance {},
	meteordalga: class extends self.ISpriteInstance {},
	meteordalga2: class extends self.ISpriteInstance {},
	ok_fuze: class extends self.ISpriteInstance {},
	fuze: class extends self.ISpriteInstance {},
	fuze_particle: class extends self.IParticlesInstance {},
	ParticlesAmbience2: class extends self.IParticlesInstance {},
	random_arrow_button: class extends self.ISpriteInstance {},
	HEALTH_BAR_ugrade3: class extends self.ISpriteInstance {},
	_2p_play_button: class extends self.ISpriteInstance {},
	EndScore: class extends self.ITextInstance {},
	ParticlesAmbience3: class extends self.IParticlesInstance {},
	kukla1: class extends self.ISpriteInstance {},
	kukla2: class extends self.ISpriteInstance {},
	kukla3: class extends self.ISpriteInstance {},
	kuklatoz: class extends self.IParticlesInstance {},
	blue_ayak_sol_clone3: class extends self.ISpriteInstance {},
	blue_ayak_sag_clone3: class extends self.ISpriteInstance {},
	el: class extends self.ISpriteInstance {},
	el1: class extends self.ISpriteInstance {},
	el2: class extends self.ISpriteInstance {},
	el3: class extends self.ISpriteInstance {},
	el4: class extends self.ISpriteInstance {},
	shield_sn_text: class extends self.ITextInstance {},
	_3arrow_sn_text: class extends self.ITextInstance {},
	helmet_sn_text: class extends self.ITextInstance {},
	pixel_particles_boom: class extends self.IParticlesInstance {},
	arm_power_miktar: class extends self.ITextInstance {},
	health_miktar: class extends self.ITextInstance {},
	arrow_damage_miktar: class extends self.ITextInstance {},
	boss_konusma: class extends self.ITextInstance {},
	ucan_kaya_or: class extends self.ISpriteInstance {},
	fire_impact_particles_black: class extends self.IParticlesInstance {},
	yildirim_expl_particle: class extends self.IParticlesInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	unlock_reward_text: class extends self.ITextInstance {},
	kan: class extends self.IParticlesInstance {},
	splash_fizik: class extends self.ISpriteInstance {},
	scar: class extends self.ISpriteInstance {},
	kan_splash: class extends self.IParticlesInstance {},
	kan_hit: class extends self.IParticlesInstance {},
	pixe_cube: class extends self.ISpriteInstance {},
	serbest: class extends self.ISpriteInstance {},
	ice_cube: class extends self.ISpriteInstance {},
	ok_drag: class extends self.ISpriteInstance {},
	gold_reward_menu2: class extends self.ISpriteInstance {},
	money_popup: class extends self.ITextInstance {},
	money_popup2: class extends self.ITextInstance {},
	gold_menu: class extends self.ISpriteInstance {},
	head_shot_text2: class extends self.ITextInstance {},
	on_off: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	or_boyun: class extends self.ISpriteInstance {},
	_2_player: class extends self.ISpriteInstance {},
	survival_mode: class extends self.ISpriteInstance {},
	BOOSTER_PANEL: class extends self.ISpriteInstance {},
	BATTLE_GO: class extends self.ISpriteInstance {},
	level_number_text: class extends self.ITextInstance {},
	SKIN_BUTTON_NEXT: class extends self.ISpriteInstance {},
	SKIN_BUTTON_PREW: class extends self.ISpriteInstance {},
	level_text: class extends self.ITextInstance {},
	fpstext: class extends self.ITextInstance {},
	level_text2: class extends self.ITextInstance {},
	kacadamm: class extends self.ISpriteInstance {},
	level_progress_bar_zemin: class extends self.ISpriteInstance {},
	progress_cube: class extends self.ISpriteInstance {},
	level_progres_text_a: class extends self.ITextInstance {},
	blue_boyun_clone3: class extends self.ISpriteInstance {},
	ucan_kaya: class extends self.ISpriteInstance {},
	Shield_button_game: class extends self.ISpriteInstance {},
	tree_arrows_button_game: class extends self.ISpriteInstance {},
	helmet_button_game: class extends self.ISpriteInstance {},
	Arm_power_alt_bar: class extends self.ISpriteInstance {},
	Health_oyun_alt_bar: class extends self.ISpriteInstance {},
	slot1: class extends self.ISpriteInstance {},
	slot2: class extends self.ISpriteInstance {},
	slot3: class extends self.ISpriteInstance {},
	slot_1_text: class extends self.ITextInstance {},
	slot_2_text: class extends self.ITextInstance {},
	slot_3_text: class extends self.ITextInstance {},
	slot_cerceve_1: class extends self.ISpriteInstance {},
	slot_cerceve_2: class extends self.ISpriteInstance {},
	slot_cerceve_3: class extends self.ISpriteInstance {},
	choose_slot1: class extends self.ISpriteInstance {},
	choose_slot2: class extends self.ISpriteInstance {},
	choose_slot3: class extends self.ISpriteInstance {},
	TUTORYAL_JOY: class extends self.ISpriteInstance {},
	TUTORYAL_JOY2: class extends self.ISpriteInstance {},
	Untitled3_0001_Layer3copy: class extends self.ISpriteInstance {},
	Untitled3_0000_Level_: class extends self.ISpriteInstance {},
	ot1: class extends self.ISpriteInstance {},
	ot2: class extends self.ISpriteInstance {},
	ot3: class extends self.ISpriteInstance {},
	ot4: class extends self.ISpriteInstance {},
	ot5: class extends self.ISpriteInstance {},
	ot6: class extends self.ISpriteInstance {},
	ot7: class extends self.ISpriteInstance {},
	ot8: class extends self.ISpriteInstance {},
	ot9: class extends self.ISpriteInstance {},
	ot10: class extends self.ISpriteInstance {},
	ot15: class extends self.ISpriteInstance {},
	level_progres_text_b: class extends self.ITextInstance {},
	level_progress_bar: class extends self.ISpriteInstance {},
	chapter_progress_bar: class extends self.ISpriteInstance {},
	level____completed: class extends self.ITextInstance {},
	next_level: class extends self.ISpriteInstance {},
	revive: class extends self.ISpriteInstance {},
	replay: class extends self.ISpriteInstance {},
	COMPLETED_MONEY: class extends self.ISpriteInstance {},
	level_money: class extends self.ITextInstance {},
	gift_10_dk: class extends self.ISpriteInstance {},
	reward_level_lock: class extends self.ITextInstance {},
	gift_20_dk: class extends self.ISpriteInstance {},
	gift_level: class extends self.ISpriteInstance {},
	level__NUMBER__completed: class extends self.ITextInstance {},
	sayac_10_dk: class extends self.ITextInstance {},
	sayac_20_dk: class extends self.ITextInstance {},
	CHAPTER_COMPLETED: class extends self.ITextInstance {},
	chapterrewards: class extends self.ITextInstance {},
	New_Arrow_Unlocked: class extends self.ITextInstance {},
	New_Archer_Unlocked: class extends self.ITextInstance {},
	level_money_effect: class extends self.ISpriteInstance {},
	shield_health: class extends self.ISpriteInstance {},
	treeok_health: class extends self.ISpriteInstance {},
	helmet_health: class extends self.ISpriteInstance {},
	helmet_health_zemin: class extends self.ISpriteInstance {},
	treeok_health_zemin: class extends self.ISpriteInstance {},
	shield_health_zemin: class extends self.ISpriteInstance {},
	_3_arrow_BAR: class extends self.ISpriteInstance {},
	shieldd_BAR: class extends self.ISpriteInstance {},
	helmet_BAR: class extends self.ISpriteInstance {},
	lock: class extends self.ISpriteInstance {},
	UNLOCK_CHAPTER_TEXT: class extends self.ITextInstance {},
	GET_REWARDS: class extends self.ISpriteInstance {},
	touch_tutorial_MENU: class extends self.ISpriteInstance {},
	skin_choose_button: class extends self.ISpriteInstance {},
	CHARACTER_TEXT: class extends self.ITextInstance {},
	tips_pano: class extends self.ISpriteInstance {},
	tutor_golge: class extends self.ISpriteInstance {},
	loading: class extends self.ITextInstance {},
	start_page_bg: class extends self.ISpriteInstance {},
	new_patlama: class extends self.IParticlesInstance {},
	expo_iz: class extends self.ISpriteInstance {},
	touch_area: class extends self.ISpriteInstance {},
	touch_area2: class extends self.ISpriteInstance {},
	dead_shoot: class extends self.ISpriteInstance {},
	head_shoot: class extends self.ISpriteInstance {},
	bonuss: class extends self.ISpriteInstance {},
	sarjor: class extends self.ISpriteInstance {},
	arm_bitti: class extends self.ISpriteInstance {},
	bonus_mesaj_text: class extends self.ITextInstance {},
	pixel_light_or: class extends self.ISpriteInstance {},
	poison_light_or: class extends self.ISpriteInstance {},
	endscre3: class extends self.ITextInstance {},
	_2p_sag_next: class extends self.ISpriteInstance {},
	_2p_sag_prew: class extends self.ISpriteInstance {},
	_2p_sol_next: class extends self.ISpriteInstance {},
	_2p_sol_prew: class extends self.ISpriteInstance {},
	healthicon_ugrade_or: class extends self.ISpriteInstance {},
	sarjor_blue: class extends self.ISpriteInstance {},
	serbest_2p_or: class extends self.ISpriteInstance {},
	serbest_2p_blue: class extends self.ISpriteInstance {},
	loading2: class extends self.ITextInstance {},
	_1_player: class extends self.ISpriteInstance {},
	healthicon_ugrade_blue: class extends self.ISpriteInstance {},
	ot11: class extends self.ISpriteInstance {},
	ot12: class extends self.ISpriteInstance {},
	ot13: class extends self.ISpriteInstance {},
	ot14: class extends self.ISpriteInstance {},
	mec_testere1: class extends self.ISpriteInstance {},
	mec_balta: class extends self.ISpriteInstance {},
	mec_kaide: class extends self.ISpriteInstance {},
	mec_uzun_kol: class extends self.ISpriteInstance {},
	MEC_KAFA_KESEN: class extends self.ISpriteInstance {},
	mec_carpan: class extends self.ISpriteInstance {},
	mec_kablo: class extends self.ISpriteInstance {},
	mec_carpan_particle: class extends self.IParticlesInstance {},
	mec_parlama: class extends self.ISpriteInstance {},
	duman: class extends self.IParticlesInstance {},
	kan_fiskiye: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_2p_ui_scr: class extends self.ISpriteInstance {},
	mec_silindir: class extends self.ISpriteInstance {},
	_2p_player_score: class extends self.ITextInstance {},
	touch_tutorial_2p_right: class extends self.ISpriteInstance {},
	touch_tutorial_2p_left: class extends self.ISpriteInstance {},
	keyboard_key_w: class extends self.ISpriteInstance {},
	keyboard_key_up: class extends self.ISpriteInstance {},
	or_fizik: class extends self.ISpriteInstance {},
	enemy_fizik: class extends self.ISpriteInstance {},
	enemy_archer: class extends self.ISpriteInstance {},
	or_archer: class extends self.ISpriteInstance {},
	hersey: class extends self.ISpriteInstance {},
	or_body: class extends self.ISpriteInstance {},
	enemy_body: class extends self.ISpriteInstance {},
	dest: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	boss_fizik: class extends self.ISpriteInstance {},
	boss_body: class extends self.ISpriteInstance {},
	blue_archer_clone3: class extends self.ISpriteInstance {},
	helmets: class extends self.ISpriteInstance {},
	choose_arrow: class extends self.ISpriteInstance {},
	blues_all: class extends self.ISpriteInstance {},
	wait_dest: class extends self.ISpriteInstance {},
	kemik: class extends self.ISpriteInstance {},
	shields: class extends self.ISpriteInstance {},
	tas_spawner: class extends self.ISpriteInstance {},
	choose_arrow_image: class extends self.ISpriteInstance {},
	choose_arrow_text: class extends self.ITextInstance {},
	finish_menu_image: class extends self.ISpriteInstance {},
	blue_archer_all: class extends self.ISpriteInstance {},
	fruit_dest: class extends self.ISpriteInstance {},
	menu_game_dest_text: class extends self.ITextInstance {},
	menu_game_destroy: class extends self.ISpriteInstance {},
	all_texts: class extends self.ITextInstance {},
	game_butn: class extends self.ISpriteInstance {},
	sahnedisiyokol: class extends self.ISpriteInstance {},
	blue_archer_all3: class extends self.ISpriteInstance {},
	kuklafizik: class extends self.ISpriteInstance {},
	blues_target: class extends self.ISpriteInstance {},
	or_archer_target: class extends self.ISpriteInstance {},
	or_archer_all: class extends self.ISpriteInstance {},
	kanlar: class extends self.IParticlesInstance {},
	boss_animation: class extends self.ISpriteInstance {},
	otlar: class extends self.ISpriteInstance {},
	finish_menu_text: class extends self.ITextInstance {},
	eller: class extends self.ISpriteInstance {},
	or_ui_lost_image: class extends self.ISpriteInstance {},
	or_ui_lost_text: class extends self.ITextInstance {},
	bomb_col: class extends self.ISpriteInstance {},
	Text_ugradepanel: class extends self.ITextInstance {},
	paticles_all: class extends self.IParticlesInstance {},
	bonusss: class extends self.ISpriteInstance {},
	mekanizma: class extends self.ISpriteInstance {}
}